apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pv-nginx-rook
spec:
  containers:
    - name: nginx
      image: nginx:mainline-alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: ejemplo-pv-rook-fs
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pv-content-rook
spec:
  containers:
    - name: content
      image: alpine:latest
      command: [ "/bin/sh", "-c" ]
      args:
        - while true; do
          date > /html/index.html;
          sleep 5;
          done
      volumeMounts:
        - name: html
          mountPath: /html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: ejemplo-pv-rook-fs
