apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pv
spec:
  containers:
    - name: nginx
      image: nginx:mainline-alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
    - name: content
      image: alpine:latest
      command: [ "/bin/sh", "-c" ]
      args:
        - if [ ! -f /html/index.html ]; then date > /html/index.html; fi;
          while true; do
          sleep 5;
          done
      volumeMounts:
        - name: html
          mountPath: /html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: ejemplo-pv
